### ISSUE TITLE
dune.3.16.1 and update the overlay

### ISSUE THREAD

**Issue by maiste** [nix-ocaml/nix-overlays#1731]
Hi :wave: 
Following the dune release guide written by @emillon, it says that the people in charge of the release should update the `nix-overlays`. As we are releasing `dune.3.16.1`, I was about to make a PR, but I have seen that you have locked the version to a specific commit. Considering `3.16.1` just does a backport for `ocaml.5.3.0` from a patch already available in `main` I imagine this is not necessary to update the overlay with the `3.16.1` version.

I wanted to make sure this is ok for you @anmonteiro. WDYT?

**Comment by anmonteiro** [comment]
@maiste the upgrade in the overlay won't sometimes make it in, but it's helpful to open the PR anyways because it tests a new dune release across many OCaml versions / packages and setups that even the opam-repo won't test, e.g. cross-compilation.

I went ahead and opened https://github.com/nix-ocaml/nix-overlays/pull/1732 to check.

**Comment by maiste** [comment]
Thanks a lot :pray:
